# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M3CciA4nYOzT7y9-4okmyQ-ZwrPCZXkX
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

pip install matplotlib seaborn

import matplotlib.pyplot as plt
import numpy as np

# 서울특별시와 자치구
districts = ['서울특별시', '종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구', '도봉구',
             '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구', '영등포구', '동작구', '관악구',
             '서초구', '강남구', '송파구', '강동구']
# 서울특별시와 자치구별 출산율
birth_rates = [0.593, 0.477, 0.606, 0.596, 0.723, 0.461, 0.62, 0.659, 0.649, 0.483, 0.573, 0.716,
               0.613, 0.607, 0.529, 0.608, 0.588, 0.684, 0.588, 0.671, 0.567, 0.422, 0.599, 0.49,
               0.598, 0.719]

# 가장 높은 출산율
max_birth_rate = max(birth_rates)

# 그래프 생성
fig, ax = plt.subplots(figsize=(14, 9))
bar_width = 0.6
bars = ax.bar(np.arange(len(districts)), birth_rates, width=bar_width, color='#98FB98')

ax.set_xlabel('자치구')
ax.set_ylabel('출산율')
ax.set_title('자치구별 출산율')
ax.set_xticks(np.arange(len(districts)))
ax.set_xticklabels(districts, rotation=90)
ax.set_ylim([0, 1])

# 가장 높은 출산율을 가진 막대의 글자 크기를 크게 조정
for i, bar in enumerate(bars):
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, yval + 0.02, round(yval, 3),
             ha='center', va='bottom', color='black' if yval != max_birth_rate else 'red', fontsize=12 if yval != max_birth_rate else 16)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 서울특별시와 자치구
districts = ['서울특별시', '종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구', '도봉구',
             '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구', '영등포구', '동작구', '관악구',
             '서초구', '강남구', '송파구', '강동구']

# 나이별 출산율 데이터 (
age_groups = ['15-19세', '20-24세', '25-29세', '30-34세', '35-39세', '40-44세', '45-49세']
birth_rates_by_age = np.array([
    [0.2,1.4,9.9,53.5,43.4,8.7,0.2],
[0,1.1,6.9,34.2,42.5,9.4,0.2],
[0,1.8,7.8,48.1,50,12.4,0.3],
[0,1.4,8.5,49,47.8,11.7,0.2],
[0.2,1.3,10,65.8,55.5,12.1,0.1],
[0,1,7.2,38.3,36,8.4,0.2],
[0,1.4,8.8,58.5,43.7,9.5,0.3],
[0.3,3,15,57,47.1,9.5,0.2],
[0.1,1.9,9.6,61.3,45.5,9.6,0.3],
[0.8,2.3,10.9,41.8,32.3,6.7,0],
[0.2,2.2,12.6,50.9,40.3,7,0.2],
[0.2,1.2,14.3,70,47.8,7.8,0.1],
[0.6,1.3,9,57.1,44.9,8.4,0.1],
[0.7,1.4,9.6,53.1,45.1,9.9,0.2],
[0,0.6,7,49.3,39.7,8.8,0,],
[0.1,1.6,14.7,57.3,38,7.3,0.2,],
[0.3,2.3,11.4,53,42.1,7.5,0.3,],
[0.4,1.6,13.1,65.9,45.7,9.5,0.1],
[0.8,1.9,13.9,49.7,41.2,9.2,0],
[0.4,1.4,9.5,57.7,52.9,12.1,0.2],
[0.1,1.3,7.8,52,42.6,8.1,0.1],
[0,1.2,4.7,31,34.1,8.8,0.2],
[0,0.8,10.5,56.2,43.3,8.1,0.2],
[0.1,0.3,7.1,44.4,37.3,7.3,0.1],
[0.3,1.1,9.3,56.9,43.6,7.9,0.2],
[0.2,2,14.7,66.8,49.3,9.7,0.2]
])

# 그래프 생성
fig, ax = plt.subplots(figsize=(16, 8))

# 꺾은 선 그래프
line_colors = sns.color_palette("husl", n_colors=len(age_groups))
for i, age_group in enumerate(age_groups):
    ax.plot(districts, birth_rates_by_age[:len(districts), i], marker='o', label=f'{age_group} 출산율', color=line_colors[i])

ax.set_xlabel('자치구')
ax.set_ylabel('출산율')
ax.set_title('자치구별 나이별 출산율')
ax.legend(loc='upper right', bbox_to_anchor=(1.2, 1))

plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()